[package]
name = "rmg"
edition = "2021"
version = "0.4.1"
build = "build.rs"
authors = ["RSUU <rsuuyu@gmail.com>"]
description = "Rust: Tiny And Fast Manga/Image Viewer"
homepage = "https://crates.io/crates/rmg"
readme = "README.md"
keywords = ["manga", "comic", "viewer"]
categories = ["Multimedia::Images"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rsuu/rmg"

[dependencies]
anyhow = "1.0.68"
cfg-if = "1.0.0"
dirs-next = "2.0.0"
gif = "0.12.0"
gif-dispose = "4.0.0"
image = "0.24.5"
imagesize = "0.11.0"
infer = "0.12.0"
lexopt = "0.3.0"
tracing = "0.1.37"
walkdir = "2.3.2"

[dependencies.asefile]
version = "0.3.5"
features = []
optional = true

[dependencies.fir]
version = "2.5.0"
features = []
optional = false
package = "fast_image_resize"

[dependencies.libheif-rs]
version = "0.15.1"
features = []
optional = true

[dependencies.minifb]
version = "0.23.0"
features = ["x11", "wayland"]
optional = false

[dependencies.resvg]
version = "0.28.0"
features = []
optional = true

[dependencies.syn]
version = "1.0.107"
features = ["parsing", "extra-traits", "full"]
optional = false
default-features = false

[dependencies.tar]
version = "0.4.38"
features = []
optional = true

[dependencies.tiny-skia]
version = "0.8.2"
features = []
optional = true

[dependencies.tracing-subscriber]
version = "0.3.16"
features = ["env-filter"]
optional = false

[dependencies.usvg]
version = "0.28.0"
features = []
optional = true

[dependencies.zip]
version = "0.6.4"
features = ["aes-crypto", "bzip2", "deflate"]
optional = true
default-features = false

[dev-dependencies]
criterion = "0.4.0"

[features]
all = ["ex_zip", "ex_tar", "de_heic"]
avx2 = []
de_all = ["de_heic", "de_aseprite", "de_svg"]
de_aseprite = ["dep:asefile"]
de_heic = ["dep:libheif-rs"]
de_svg = ["dep:usvg", "dep:tiny-skia", "dep:resvg"]
default = ["ex_zip", "ex_tar"]
ex_tar = ["dep:zip"]
ex_zip = ["dep:tar"]
sse4_1 = []
[profile.release]
opt-level = 2
debug = false
lto = "thin"
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
strip = true
[profile.release.package."*"]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
opt-level = 2
strip = true

[[bench]]
name = "bench_main"
plugin = false
proc-macro = false
harness = false
required-features = []
