[package]
name = "rmg"
edition = "2021"
version= "0.5.7"
authors = ["RSUU <rsuuyu@gmail.com>"]
description = "Rust: Tiny And Fast Manga/Image Viewer"
homepage = "https://crates.io/crates/rmg"
readme = "README.md"
keywords = ["manga", "comic", "viewer"]
categories = ["Multimedia::Images"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rsuu/rmg"

[profile.release]
lto = "thin"
opt-level = 2
codegen-units = 1
panic = "abort"
overflow-checks = false
debug = false
debug-assertions = false
incremental = false
strip = true

[profile.release.package."*"]
opt-level = 2
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
strip = true

[dependencies]
anyhow = "1.0.68"
infer = "0.12.0"      # filetype
lexopt = "0.3.0"      # cli
walkdir = "2.3.2"     # fs
dirs-next = "2.0.0"   # config
sysinfo = {version="0.27.7" ,default-features = false}
cfg-if = "1"

# log
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

#log = "0.4.17"
#env_logger = {version = "0.10.0", features = ["color"], default-features = false}

# image
fir = {version = "2.5.0", package = "fast_image_resize"}
asefile={version = "0.3.5",optional = true}
libheif-rs = {version = "0.15.1",optional = true}
gif = "0.12.0"
gif-dispose = "4.0.0"
image = "0.24.5"

# window
minifb={version = "0.23.0",features = ["x11", "wayland"]}

# config
syn={version = "1.0.107",features = ["parsing", "extra-traits", "full"],default-features = false}

# svg
tiny-skia={version = "0.8.2",optional = true}
usvg={version = "0.28.0",optional = true}
resvg={version = "0.28.0",optional = true}

# archive
zip ={version = "0.6.4",features = ["aes-crypto", "bzip2", "deflate"],optional = true,default-features = false}
tar ={version = "0.4.38",optional = true}

[features]
default = ["ex_zip", "ex_tar"]
all = ["ex_all", "de_all"]
ex_all = ["ex_tar", "ex_zip"]
de_all = ["de_heic", "de_aseprite", "de_svg"]
de_aseprite = ["dep:asefile"]
de_heic = ["dep:libheif-rs"]
de_svg = ["dep:usvg", "dep:tiny-skia", "dep:resvg"]
ex_tar = ["dep:zip"]
ex_zip = ["dep:tar"]
sse4_1 = []
avx2 = []

[[bench]]
name = "bench_main"
plugin = false
proc-macro = false
harness = false
required-features = []

# bench
[dev-dependencies]
criterion = "0.4.0"
