[package]
name = "rmg"
version = "0.0.4"
edition = "2021"
authors = ["RSUU <rsuuyu@gmail.com>"]
description = "Manga Reader"
readme = "README.md"
homepage = "https://crates.io/crates/rmg"
repository = "https://github.com/rsuu/rmg"
license = "MIT OR Apache-2.0"
keywords = ["manga","comic"]
#categories = []
autobenches = true



[dependencies]
# fs
tempfile = "3.2.0"
walkdir = "2.3.2"

# archive
tar = "0.4.37"
zip = "0.5.13"
zstd = "0.11.2"

# filetype
infer =  "0.3"

# color
rgb = "0.8.32"

# image
sdl2 = { version = "0.34.5", features = ["image", "ttf"] }
image = "0.24.2"
fast_image_resize = "0.9.5"

# args
lexopt = "0.2.0"
glob = "0.3.0"

# other
#rayon = "1.5.3"
tokio = { version = "1.19.2", features = ["full"] }

# metadata
byteorder = "1.4.3"
miniserde = "0.1.24"

# bench
criterion = "0.3.5"

# metadata
speedy = "0.8.2"

# config
syn = { version = "1.0.98", features = ["full", "extra-traits"] }


[[bench]]
name = "bench_main"
harness = false

