[package]
name = "rmg"
version = "0.0.2"
edition = "2021"
authors = ["RSUU <rsuuyu@gmail.com>"]
description = "A Manga Reader"
readme = "README.md"
homepage = "https://crates.io/crates/rmg"
repository = "https://github.com/rsuu/rmg"
license = "MIT OR Apache-2.0"

[dependencies]
# files
tempfile = "3.2.0"
tar = "0.4.37"
zip = "0.5.13"

# filetype
infer =  "0.3"

# color
rgb = "0.8.32"

# image
sdl2 = { version = "0.34.5" , features = ["image"]}
image = "0.24.2"
fast_image_resize = "0.9.5"

# args
lexopt = "0.2.0"
glob = "0.3.0"

# other
#rayon = "1.5.3"
tokio = { version = "1.19.2", features = ["full"] }
byteorder = "1.4.3"
miniserde = "0.1.24"
