[package]
name = "rmg"
version = "0.2.4"
edition = "2021"
authors = ["RSUU <rsuuyu@gmail.com>"]
description = "Rust: Tiny Manga/Image Viewer"
readme = "README.md"
homepage = "https://crates.io/crates/rmg"
repository = "https://github.com/rsuu/rmg"
license = "MIT OR Apache-2.0"
keywords = ["manga","comic"]
#categories = []
autobenches = true
build = "build.rs"

[profile.release]
strip = true
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = "abort"

[dependencies]
# fs
#tempfile = "3.3.0"
walkdir = "2.3.2"
dirs-next = "2.0.0"

# archive
tar = {version="0.4.38", optional = true }
#zstd = "0.11.2"
zip = { version = "0.6.3", default-features = false, features = ["aes-crypto","bzip2","deflate", ], optional = true  }

# filetype
infer = "0.9.0"

# window
#sdl2 = { version = "0.35.2", features = ["image", "ttf"] }
minifb = { version = "0.23.0", features = ["x11", "wayland"] }

# image
image = { version = "0.24.4" }
fir = {package="fast_image_resize"  ,version="1.0.0"}
libheif-rs = { version = "0.15.0", optional = true }
asefile ={ version = "0.3.5", optional = true }
#   gif
gif = "0.12.0"
gif-dispose = "4"
#   svg
usvg = "0.27.0"
tiny-skia = "0.8.2"
resvg = "0.27.0"

# args
lexopt = "0.2.1"

# config
syn = { version = "1.0.102", features = ["full", "extra-traits"] }

# async
#pollster = "0.2.5"

# other
cfg-if = "1.0.0"

# debug
log = "0.4.17"
simple_logger = { version = "2.3.0", features = ["colors", "threads"] }


[dev-dependencies]
# benchmark
criterion = "0.4.0"

[[bench]]
name = "bench_main"
harness = false

[features]
default = ["ex_zip", "ex_tar"]
all = ["ex_zip", "ex_tar", "de_heic"]

# archive
ex_zip = ["dep:tar"]
ex_tar = ["dep:zip"]

# resize
sse4_1 = []
avx2 = []

# image
de_heic = ["dep:libheif-rs"]
de_ase = ["dep:asefile"]
